package edu.umn.csci5801.model;

/**
 * Created by zihong on 12/3/14.
 */
public enum  Reqs {
    BREADTH_REQUIREMENT_PHD,
    BREADTH_REQUIREMENT_MS,
    THESIS_PHD,
    THESIS_MS,
    PLAN_B_PROJECT,
    COLLOQUIUM,
    OUT_OF_DEPARTMENT,
    PHD_LEVEL_COURSES,
    PHD_LEVEL_COURSES_PLANC,
    INTRO_TO_RESEARCH,
    TOTAL_CREDITS,
    COURSE_CREDITS,
    OVERALL_GPA_PHD,
    IN_PROGRAM_GPA_PHD,
    OVERALL_GPA_MS,
    IN_PROGRAM_GPA_MS,
    MILESTONES_PHD,
    MILESTONES_MS_A,
    MILESTONES_MS_B,
    MILESTONES_MS_C

}
